config/routes.rb
# frozen_string_literal: true

require 'api_constraints'
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'background_jobs/give_inventory'
  match '/404', to: 'errors#not_found', via: :all
  match '/400', to: 'errors#bad_request', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get 'public/available_parcels'
  get 'public/my_parcels'
  get 'public/my_purchases'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

  get 'pages/home' => 'pages#home'
  get 'pages/products' => 'pages#products'
  get 'pages/pricing' => 'pages#pricing'
  get 'pages/documentation' => 'pages#documentation'
  get 'pages/faqs' => 'pages#faqs'

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Sidekiq::Web => '/sidekiq'

  namespace :async, defaults: { format: 'json' } do
    resources :donations, only: [:index]
    resources :visits, only: [:index]
    resources :tips, only: [:index]
    resources :sales, only: [:index]
    resources :rentals, only: [:index]
    resources :shop_rentals, only: [:index]
    resources :service_board_rentals, only: [:index]
    resources :payroll, only: [:index]
  end

  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :abstract_web_objects, only: [:create]
      resources :users, except: %i[index new edit], param: :avatar_key
      resources :service_tickets, except: %i[destroy edit new]
      namespace :rezzable do
        resources :terminals, except: %i[index new edit]
        resources :servers, except: %i[new edit]
        resources :donation_boxes, except: %i[index new edit]
        resources :traffic_cops, except: %i[index new edit]
        resources :tip_jars, except: %i[index new edit]
        resources :vendors, except: %i[index new edit]
        resources :parcel_boxes, except: %i[index new edit]
        resources :tier_stations, except: %i[index new edit]
        resources :shop_rental_boxes, except: %i[index new edit]
        resources :service_boards, except: %i[index new edit]
        resources :time_cops, except: %i[index new edit]
        resources :web_objects
      end
      namespace :analyzable do
        resources :inventories, except: %i[new edit]
        resources :parcels, except: %i[new edit destroy]
        resources :transactions, only: %i[create]
        resources :employees, except: %i[new edit] do
          member do
            put 'pay'
          end
          collection do
            put 'pay_all'
          end
        end
      end
    end
  end
end

app/views/shared/_footer.html.erb
   <!--main-footer -->
    <footer class="main-footer">
        <div class="auto-container">
            <div class="footer-top">
                <div class="widget-section wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
                    <div class="row clearfix">
                        <div class="col-lg-3 col-md-6 col-sm-12 footer-column">
                            <div class="footer-widget logo-widget">
                                <figure class="footer-logo">
                                    <a href="index.html">
                                        <%= image_tag('logo_name_48x315.png') %>
                                    </a>
                                </figure>
                                <div class="text">
                                    <p><%= I18n.t('web_site.mission_statement') %></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-12 footer-column">
                            <div class="footer-widget links-widget">
                                <div class="widget-title">
                                    <h3>Quick Link</h3>
                                </div>
                                <div class="widget-content">
                                    <ul>
                                        <li><a href="blog-masonry.html">Company History</a></li>
                                        <li><a href="blog-masonry.html">About Us</a></li>
                                        <li><a href="blog-masonry.html">Contact Us</a></li>
                                        <li><a href="blog-masonry.html">Services</a></li>
                                        <li><a href="blog-masonry.html">Privacy Policy</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!--<div class="col-lg-3 col-md-6 col-sm-12 footer-column">-->
                        <!--    <div class="footer-widget links-widget">-->
                        <!--        <div class="widget-title">-->
                        <!--            <h3>Services</h3>-->
                        <!--        </div>-->
                        <!--        <div class="widget-content">-->
                        <!--            <ul>-->
                        <!--                <li><a href="blog-masonry.html">Company History</a></li>-->
                        <!--                <li><a href="blog-masonry.html">About Us</a></li>-->
                        <!--                <li><a href="blog-masonry.html">Contact Us</a></li>-->
                        <!--                <li><a href="blog-masonry.html">Services</a></li>-->
                        <!--                <li><a href="blog-masonry.html">Privacy Policy</a></li>-->
                        <!--            </ul>-->
                        <!--        </div>-->
                        <!--    </div>-->
                        <!--</div>-->
                        <div class="col-lg-3 col-md-6 col-sm-12 footer-column">
                            <div class="footer-widget contact-widget">
                                <div class="widget-title">
                                    <h3>Contact Info</h3>
                                </div>
                                <div class="widget-content">
                                    <ul>
                                        <li>Flat 20, Reynolds Neck, North Hele naville, FV77 8WS</li>
                                        <li><a href="tel:23055873407">+2(305) 587-3407</a></li>
                                        <li><a href="mailto:info@example.com">info@example.com</a></li>
                                    </ul>
                                </div>
                                <ul class="social-links clearfix">
                                    <!--<li><a href="blog-masonry.html"><i class="fab fa-facebook-f"></i></a></li>-->
                                    <li><a href="blog-masonry.html"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="blog-masonry.html"><i class="fab fa-discord"></i></a></li>
                                    <!--<li><a href="blog-masonry.html"><i class="fab fa-linkedin-in"></i></a></li>-->
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-bottom clearfix">
                <div class="copyright pull-left">
                    <p><a href="index.html">SLapp Data</a> &copy; 2021 All Right Reserved</p>
                </div>
                <!--<ul class="footer-nav pull-right">-->
                <!--    <li><a href="blog-masonry.html">Terms of Service</a></li>-->
                <!--    <li><a href="blog-masonry.html">Privacy Policy</a></li>-->
                <!--</ul>-->
            </div>
        </div>
    </footer>
     <!--main-footer end -->

app/views/shared/_header.html.erb
 <header class="main-header">
        <div class="outer-container">
            <div class="header-upper clearfix">
                <div class="outer-box pull-left">
                    <div class="logo-box pull-left">
                        <figure class="logo">
                            <%= link_to root_path do %>
                                <%= image_tag("logo_32_no_bkgnd.png", alt: "") %>
                                &nbsp;SL<span class="highlight">app </span>Data
                            <% end %>
                        </figure>
                    </div>
                    <div class="menu-area pull-left">
                        <!--Mobile Navigation Toggler-->
                        <div class="mobile-nav-toggler">
                            <i class="icon-bar"></i>
                            <i class="icon-bar"></i>
                            <i class="icon-bar"></i>
                        </div>
                        <nav class="main-menu navbar-expand-md navbar-light">
                            <div class="collapse navbar-collapse show clearfix" id="navbarSupportedContent">
                                <ul class="navbar-nav navigation clearfix">
                                    <li class="nav-item <%= 'active' if action_name == 'home' || action_name.nil? %>">
                                        <%= link_to 'Home', pages_home_path %>
                                    </li> 
                                    <li class="nav-item dropdown <%= 'active' if action_name == 'products' %>">
                                        <%= link_to 'Products', pages_products_path %>
                                    </li>
                                    <li class = "nav-item dropdown <%= 'active' if action_name == 'pricing' %>">
                                        <%= link_to 'Pricing', pages_pricing_path %>
                                    </li>
                                    <li class = "nav-item dropdown <%= 'active' if action_name == 'documentation' %>">
                                        <%= link_to "Documentation", pages_documentation_path %>
                                    </li>
                                    <li class = "nav-item dropdown <%= 'active' if action_name == 'faqs' %>">
                                        <%= link_to "FAQs", pages_faqs_path %>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
                <div class="outer-box pull-right">
                    <div class="menu-left-content pull-left">
                        <nav class="main-menu navbar-expand-md navbar-light">
                            <div class="collapse navbar-collapse show clearfix" id="navbarSupportedContent">
                                
                                <ul class="navigation user-nav clearfix">
                                    
                                    <li><%= link_to "Visit Us In World" , 
                                                    "https://#{Settings.default.visit_us_slurl}",
                                                        class: 'slurl' %></li>
                                    <li class="dropdown">
                                        <% if current_user %>
                                            <a href="#"><%= current_user.avatar_name %></a>
                                            <ul>
                                                <li>
                                                    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
                                                </li>
                                                <li>
                                                    <%= link_to 'My stuff', my_dashboard_path %>
                                                </li>
                                                <% if current_user.can_be_admin? %>
                                                    <li>
                                                        <%= link_to 'Admin stuff', admin_dashboard_path %>
                                                    </li>
                                                <% end %>
                                            </ul>
                                        <% else %>
                                            <%= link_to 'Login', new_user_session_path %>
                                        <% end %>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                        
                    </div>
                    
                </div>

            </div>
        </div>

        <!--sticky Header-->
        <div class="sticky-header">
            <div class="container clearfix">                        
                <figure class="logo">
                    <%= link_to '/' do %>
                        <%= image_tag("logo_32_no_bkgnd.png", alt: "") %>
                        &nbsp;SL<span class="highlight">app </span>Data
                    <% end %>
                </figure>
                <div class="menu-area">
                    <nav class="main-menu clearfix">
                        <!--Keep This Empty / Menu will come through Javascript-->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- main-header end -->

    <!-- Mobile Menu  -->
    <div class="mobile-menu">
        <div class="menu-backdrop"></div>
        <div class="close-btn"><i class="fas fa-times"></i></div>
        
        <nav class="menu-box">
            <div class="nav-logo"><a href="index.html"><%= image_tag("theme/logo-2.png", alt: "", title: "") %></a></div>
            <div class="menu-outer"><!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header--></div>
            <div class="contact-info">
                <h4>Contact Info</h4>
                <ul>
                    <li>Chicago 12, Melborne City, USA</li>
                    <li><a href="tel:+8801682648101">+88 01682648101</a></li>
                    <li><a href="mailto:info@example.com">info@example.com</a></li>
                </ul>
            </div>
            <div class="social-links">
                <ul class="clearfix">
                    <li><a href="index.html"><span class="fab fa-twitter"></span></a></li>
                    <li><a href="index.html"><span class="fab fa-facebook-square"></span></a></li>
                    <li><a href="index.html"><span class="fab fa-pinterest-p"></span></a></li>
                    <li><a href="index.html"><span class="fab fa-instagram"></span></a></li>
                    <li><a href="index.html"><span class="fab fa-youtube"></span></a></li>
                </ul>
            </div>
        </nav>
    </div><!-- End Mobile Menu -->